version: "3.2"
services:
  bitcoin:
    image: ruimarinho/bitcoin-core
    command:
      [
        "-printtoconsole",
        "-txindex",
        "-regtest=1",
        "-rpcallowip=172.18.0.0/16",
        "-rpcbind=0.0.0.0",
        "-rpcuser=user",
        "-rpcpassword=pass",
        "-fallbackfee=0.00001"
      ]
    networks:
      net:
        ipv4_address: 172.18.2.1
    tty: true
    ports:
      - 18443:18443
    volumes:
      - ./tmp/bitcoin:/home/bitcoin/.bitcoin/regtest
      - ./conf/:/home/bitcoin/conf
  electrs:
    build: ./electrs
    command:
      [
        "electrs",
        "-vvvv",
        "--timestamp",
        "--daemon-dir",
        "/tmp/.bitcoin",
        "--db-dir",
        "/tmp/db",
        "--network",
        "regtest",
        "--electrum-rpc-addr",
        "0.0.0.0:50001",
        "--daemon-rpc-addr",
        "bitcoin:18443",
        "--cookie-file",
        "/home/user/conf/electrs.cookie",
        "--txid-limit",
        "0",
      ]
    networks:
      net:
        ipv4_address: 172.18.4.1
    tty: true
    ports:
      - 50002:50001
    volumes:
      - ./tmp/electrs/db:/tmp/db
      - ./tmp/bitcoin:/tmp/.bitcoin/regtest
      - ./conf/:/home/user/conf
  esplora:
    build: ./esplora
    command:
      [
        "electrs",
        "-vvvv",
        "--timestamp",
        "--daemon-dir",
        "/tmp/.bitcoin",
        "--db-dir",
        "/tmp/db",
        "--network",
        "regtest",
        "--electrum-rpc-addr",
        "0.0.0.0:50001",
        "--daemon-rpc-addr",
        "bitcoin:18443",
        "--http-addr",
        "0.0.0.0:3000",
        "--cookie",
        "user:pass",
        "--electrum-txs-limit",
        "1000000",
        "--utxos-limit",
        "1000000"
      ]
    networks:
      net:
        ipv4_address: 172.18.5.1
    tty: true
    ports:
      - 50003:50001
      - 3001:3000
    volumes:
      - ./tmp/esplora/db:/tmp/db
      - ./tmp/bitcoin:/tmp/.bitcoin/regtest
networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
volumes:
  bitcoin:
    driver: local
  electrs:
    driver: local
  esplora:
    driver: local
